### ISSUE TITLE
[bug] node.close.value not correct

### ISSUE THREAD

**Issue by songhlc** [acrazing/html5parser#6]
**version: 1.1.2**

use case:
```
<Test></Test>
```
**expect:**
1.node. rawName: Test
2.node.open.value: `<Test>`
3.node.close.value: `</Test>`

**actual result:**
- [x] 1.node.rawName:Test
- [x] 2.node.open.value : `<Test>`
- [ ] 3.node.close.value: `</test>`

got wrong node.close.value

**Comment by acrazing** [comment]
Something goes wrong when processing case insensitive tag names, you should not use `tag.open` or `tag.close` directly, because it is not normalized. For example, `<diV></DIv>` will be parsed as a tag, the result `name` is `div`, `rawName` is `diV`, the `close` is a text `</Div>`. You should use `name` or `rawName` according to your requirements.

But any way, it is `</Test>` now!
